name: Scrape RCDB Roller Coasters
on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
env:
  RCDB_URL: ${{ vars.RCDB_URL }}
jobs:
  scrape-coasters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm run scrape
          git config user.name rcdb-api-bot
          git config user.email bot@rcdb-api.com
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update RCDB Roller Coasters database"
          git push origin main
